# Meta Data for SEO

## Homepage
title = "Pavithra"
titleSeparator = " | "
titleAddition = "Hi!"
description = "Pavithra's home page."

## Open Graph + Twitter Cards
images = [""]
twitterSite = "pavithraes"
twitterCreator = "pavithraes"
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = ""
schemaTwitter = "https://twitter.com/pavithraes"
schemaLinkedIn = "https://www.linkedin.com/in/pavithra-eswaramoorthy-47977b146/"
schemaGitHub = "https://github.com/pavithraes"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "© 2021 Pavithra Eswaramoorthy"

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = ""
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
